Refactor/using dto for both city-component and coord-component
PouxvielAdrien/PouxvielAdrien.github.io pull request #2
Opened 2022-07-13 13:45 UTC by PouxvielAdrien

2022-07-13 14:45 UTC, fabiendv requested changes
Good job for a first step! Let's keep going ;)

2022-07-13 14:45 UTC, fabiendv commented on src/app/_core/models/dtos.ts
> +  weather:{id:number;
Can you add a return? The display should look like the `main` object above.
PS: it would be nice to use a linter ;)

2022-07-13 14:45 UTC, fabiendv commented on src/app/_core/models/forecast.ts
> +        // console.log("tempMin : ", tempMin)
Can you remove all those commented lines?

2022-07-13 14:45 UTC, fabiendv commented on src/app/_core/models/weather-api-response.ts
>  export interface WeatherApiResponse {
Why this one still exist?

2022-07-13 14:45 UTC, fabiendv commented on src/app/_core/models/forecast-fetch.ts
> +export class ForecastFetch {
You can get rid of this one as well

2022-07-13 14:45 UTC, fabiendv commented on src/app/_core/services/weather.service.ts
> +  /***** Angular HttpClientModule for API calls *****/
- Not relevant comment
- Wrong syntax. Must be like this (depending of your params):
![image](https://user-images.githubusercontent.com/37407695/178761453-aa46a3d4-8c7c-4afe-920d-645f6199d246.png)

2022-07-13 14:45 UTC, fabiendv commented on src/app/_core/services/weather.service.ts
> +        map(response => constructWeatherFromApiData(response, lang, unit))
Can you refactor this method the same way?

- [ ] Remove CurrentWeather
- [ ] Remove WeatherApiResponse
- [ ] Remove construc.... (use contructor)

2022-07-13 14:45 UTC, fabiendv commented on src/app/_core/services/weather.service.ts
> +        map(response => new Forecast(response, lang, units))
Clean & perfect !

2022-07-13 14:45 UTC, fabiendv commented on src/app/current-city/current-city.component.html
> +            <div class="card" *ngFor="let Day of weathers, let i = index;">
`Day` must be `day`

2022-07-13 14:45 UTC, fabiendv commented on src/app/current-city/current-city.component.ts
> +    this.queryParamsSubscription?.unsubscribe();
Did Ahmed tell you this?

2022-07-13 14:45 UTC, fabiendv commented on src/example.js
> +
????????????

2022-07-13 14:45 UTC, fabiendv commented on src/app/forecast-coord/forecast-coord.component.ts
> +  ShowForecast(){
wrong capital letter

2022-07-13 14:55 UTC, PouxvielAdrien commented on src/app/_core/models/weather-api-response.ts
>  export interface WeatherApiResponse {
For the previous API calls I made. (with HttpModuleCLient too). I constructed it with Ahmed.

2022-07-13 15:07 UTC, PouxvielAdrien commented on src/app/current-city/current-city.component.ts
> +    this.queryParamsSubscription?.unsubscribe();
Yeah it's to be sure the  query params are well destroyed and not have conflicts.

2022-07-13 15:08 UTC, PouxvielAdrien commented on src/example.js
> +
Have forgotten to delete this

2022-07-13 15:58 UTC, fabiendv requested changes

2022-07-13 15:58 UTC, fabiendv commented on src/app/forecast-coord/forecast-coord.component.ts
> +      }
This needs to be inserted inside the weather class constructor somehow

2022-07-15 11:02 UTC, fabiendv requested changes
Nice DTO pattern!
With those 3 last quick changes, it will be perfect and ready to be merged 🚀

2022-07-15 11:02 UTC, fabiendv commented on src/app/_core/models/dtos.ts
> +  name:string;
Now we do not use ‘name’ right?

2022-07-15 11:02 UTC, fabiendv commented on src/app/_core/models/dtos.ts
> +  list: WeatherDto[];
Cod and other missing

2022-07-15 11:02 UTC, fabiendv commented on src/app/_core/models/weather.ts
> +  weatherDescription: string | null = null;
You can call it ‘description’ since it is linked to the weather class

2022-07-15 11:18 UTC, PouxvielAdrien commented on src/app/_core/models/dtos.ts
> +  name:string;
No I'm using it for the 'Current Weather' Api calls

2022-07-15 11:28 UTC, fabiendv approved these changes

2022-07-18 09:06 UTC, merged